export default function(id,startRoundOne, endRoundOne, startRoundTwo,endRoundTwo,startRoundThree,endRoundThree   ){
return{
    id,
    activeRound:'Not-Started',
    status:'Not-Started',
    round1:{
        startAt:startRoundOne,
        endAt:endRoundOne,
        winner:false,
        currentIndex:0,
        q1:{
            answer:'BIFOCAL',
            answer2:'BIF0CAL',
            solvedAt:null,
            solved:false
        },
        q2:{
            answer:'RICHARD',
            solvedAt:null,
            solved:false
        },
        q3:{
            answer:'KITE',
            solvedAt:null,
            solved:false
        },
        q4:{
            answer:'ORDER',
            solvedAt:null,
            solved:false
        },
        q5:{
            answer:'LEYDEN',
            solvedAt:null,
            solved:false
        },
        q6:{
            answer:'JOHN ADAMS',
            answer2:'JOHNADAMS',
            solvedAt:null,
            solved:false
        },
        q7:{
            answer:'BOSTON',
            solvedAt:null,
            solved:false
        },
    },
    round2:{
        startAt:startRoundTwo,
        endAt:endRoundTwo,
    },
    round3:{
        currentIndex:0,
        startAt:startRoundThree,
        endAt:endRoundThree,
        q1:{
            answer:'REGIUS',
            solvedAt:null,
            solved:false
        },
        q2:{
            answer:'UNICORN',
            solvedAt:null,
            solved:false
        },
    }
}
}